name: EAC
main: DarkWav\EAC\EAC
version: 1.3.1
load: STARTUP
author: DarkWav (Darku)
api: ["3.0.0",2.1.0","2.0.0","1.14.0","1.13.2","1.0.0"]
commands:
      eac:
           description: EAC main command
           aliases: ["AntiCheat","EAC"]
permissions:
    eac:
        default: op
        description: "Allows to use all EAC features."
children:
    eac.bypass:
        default: op
        description: "Allows to bypass AntiForceGameMode."